name: Run Zerodha News Scrapper

on:
  schedule:
    - cron: "30 13 * * *"
  workflow_dispatch:

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@4

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install Dependencies
        run: npm install

      - name: create .env file
        run: |
          echo "GROQ_API_KEY=${{ secrets.GROQ_API_KEY }}" >> .env
          echo "WP_API_URL=${{ secrets.WP_API_URL }}" >> .env
          echo "WP_EXTRA_API_URL=${{ secrets.WP_EXTRA_API_URL }}" >> .env
          echo "WP_USER=${{ secrets.WP_USER }}" >> .env
          echo "WP_PASS=${{ secrets.WP_PASS }}" >> .env
          echo "SHEET_ID=${{ secrets.SHEET_ID }}" >> .env
          echo "SHEET_NAME=Sheet1" >> .env
          echo "GOOGLE_SERVICE_ACCOUNT_EMAIL=${{ secrets.GOOGLE_SERVICE_ACCOUNT_EMAIL }}" >> .env
          echo "GOOGLE_PRIVATE_KEY=${{ secrets.GOOGLE_PRIVATE_KEY }}" >> .env

      - name: Run Script
        run: node index.js
